name: Deploy CSV Processor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test application
      run: |
        python -c "import main; print('✅ Application loads successfully')"
    
    - name: Test CSV processing
      run: |
        python -c "
        import pandas as pd
        import tempfile
        import os
        
        # Create test CSV
        test_data = {
            'Schedule Name': ['Test'],
            'First Name': ['John'],
            'Last Name': ['Doe'],
            'Email': ['john@example.com'],
            'Primary Phone': ['123-456-7890'],
            'Secondary Phone': [''],
            'Mobile Phone': ['Jane Doe'],
            'Student': ['0.00'],
            'Total Balance': ['0.00'],
            'Schedule Balance': ['0.00'],
            'Birthday': ['01-01-2000'],
            'Special Instructions': [''],
            'Student First Name': ['Jane'],
            'Student Last Name': ['Doe'],
            'Gender': ['5'],
            'Grade': ['Teacher'],
            'Teacher': ['Parent Pick Up'],
            'Parent Pickup': ['Parent Name'],
            'Authorized to Pickup': ['Yes'],
            'Photo Release': ['123 Main St'],
            'Address': ['City'],
            'City': ['State'],
            'State': ['12345'],
            'Zipcode': ['Location'],
            'Location': ['']
        }
        
        df = pd.DataFrame(test_data)
        
        # Test the processing logic
        filtered_df = pd.DataFrame({
            'Student': df.iloc[:, 6],  # Mobile Phone column
            'Grade': df.iloc[:, 14],   # Gender column
            'Photo Release': df.iloc[:, 18],  # Authorized to Pickup column
            'Parent Pickup': df.iloc[:, 17]  # Parent Pickup column
        })
        
        print('✅ CSV processing test passed')
        print(f'Filtered data: {filtered_df.iloc[0].to_dict()}')
        "
